apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: project-bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: your-dockerhub-username/ui:latest
          ports:
            - containerPort: 80
          env:
            # Point UI to backend services
            - name: CATALOG_SERVICE_URL
              value: http://catalog:8080
            - name: ORDERS_SERVICE_URL
              value: http://orders:8080
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: project-bedrock
spec:
  type: LoadBalancer   # expose externally
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
